"""initial schema

Revision ID: 9827c44cef3f
Revises: 
Create Date: 2026-07-29 04:23:40.978258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9827c44cef3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_cover_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_name', sa.String(length=60), nullable=False),
    sa.Column('round', sa.String(length=20), nullable=False),
    sa.Column('grass_cover_pct', sa.Float(), nullable=True),
    sa.Column('perennial_grass_pct', sa.Float(), nullable=True),
    sa.Column('annual_grass_pct', sa.Float(), nullable=True),
    sa.Column('bare_ground_pct', sa.Float(), nullable=True),
    sa.Column('litter_pct', sa.Float(), nullable=True),
    sa.Column('woody_cover_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_cover_rounds_plot_name'), 'reference_cover_rounds', ['plot_name'], unique=False)
    op.create_index(op.f('ix_reference_cover_rounds_round'), 'reference_cover_rounds', ['round'], unique=False)
    op.create_table('reference_plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_name', sa.String(length=60), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=True),
    sa.Column('ecoregion', sa.String(length=160), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('perennial_grass_pct', sa.Float(), nullable=True),
    sa.Column('annual_grass_pct', sa.Float(), nullable=True),
    sa.Column('grass_cover_pct', sa.Float(), nullable=True),
    sa.Column('bare_ground_pct', sa.Float(), nullable=True),
    sa.Column('litter_pct', sa.Float(), nullable=True),
    sa.Column('woody_cover_pct', sa.Float(), nullable=True),
    sa.Column('standing_crop_estimate', sa.Float(), nullable=True),
    sa.Column('biomass_clipped', sa.Float(), nullable=True),
    sa.Column('woody_mean_height', sa.Float(), nullable=True),
    sa.Column('woody_seedlings', sa.Float(), nullable=True),
    sa.Column('cattle_count', sa.Integer(), nullable=True),
    sa.Column('goat_count', sa.Integer(), nullable=True),
    sa.Column('sheep_count', sa.Integer(), nullable=True),
    sa.Column('rotational_grazing', sa.String(length=20), nullable=True),
    sa.Column('rainfall_note', sa.String(length=400), nullable=True),
    sa.Column('dominant_herbaceous', sa.String(length=300), nullable=True),
    sa.Column('dominant_woody', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_plots_ecoregion'), 'reference_plots', ['ecoregion'], unique=False)
    op.create_index(op.f('ix_reference_plots_plot_name'), 'reference_plots', ['plot_name'], unique=True)
    op.create_table('camps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('cattle_count', sa.Integer(), nullable=False),
    sa.Column('goat_count', sa.Integer(), nullable=False),
    sa.Column('sheep_count', sa.Integer(), nullable=False),
    sa.Column('other_livestock', sa.String(length=300), nullable=True),
    sa.Column('grazing_start_date', sa.Date(), nullable=True),
    sa.Column('rotational_grazing', sa.Boolean(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_farm_id'), 'camps', ['farm_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('direct_answer', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=40), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('herd_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weather_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('photo_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_camp_id'), 'assessments', ['camp_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('camp_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_camp_id'), 'chat_messages', ['camp_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_farm_id'), 'chat_messages', ['farm_id'], unique=False)
    op.create_table('camp_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camp_photos_assessment_id'), 'camp_photos', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_camp_photos_camp_id'), 'camp_photos', ['camp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_camp_photos_camp_id'), table_name='camp_photos')
    op.drop_index(op.f('ix_camp_photos_assessment_id'), table_name='camp_photos')
    op.drop_table('camp_photos')
    op.drop_index(op.f('ix_chat_messages_farm_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_camp_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_assessments_camp_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_camps_farm_id'), table_name='camps')
    op.drop_table('camps')
    op.drop_index(op.f('ix_reference_plots_plot_name'), table_name='reference_plots')
    op.drop_index(op.f('ix_reference_plots_ecoregion'), table_name='reference_plots')
    op.drop_table('reference_plots')
    op.drop_index(op.f('ix_reference_cover_rounds_round'), table_name='reference_cover_rounds')
    op.drop_index(op.f('ix_reference_cover_rounds_plot_name'), table_name='reference_cover_rounds')
    op.drop_table('reference_cover_rounds')
    op.drop_table('farms')
    # ### end Alembic commands ###
